pull_request_rules:
  - name: automatic merge project when conditions are met
    conditions:
      - status-success=now
      - "#approved-reviews-by>=2"
      - base=staging
      - label=project
      - label!=WIP
      - label!=ready%20for%20review
      - files=data/posts-manifest.js
      - "#files=2"
    actions:
      delete_head_branch: {}
      merge:
        method: rebase
        method: merge
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=now
      - base=staging
    actions:
      delete_head_branch: {}
      merge:
        method: rebase
        method: merge
